#!/bin/sh -e

case "$1" in
	install)
		;;
	upgrade)
		pycentral pkgremove python-constraint || true
		;;
	abort-upgrade)
		;;
	*)
		echo "preinst called with unknown argument '$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
